### ISSUE TITLE
Discordclient Singleton

### ISSUE THREAD

**Issue by nramirez** [kajahno/elprimobot#40]
We might be calling the server many times, and sometimes there might be concurrent calls, to make well use of resources/quota and easily handle Discord client initialization we can have a singleton https://refactoring.guru/design-patterns/singleton

**Comment by TomasGonzalez** [comment]
I suggest we don't use singleton, or class components all-together as they're often seeing as anti-patterns in js, and can easily lead to un maintainable code. Instead propose we explore the dependency injection approach, or the hoc patter. https://medium.com/geekculture/dependency-injection-in-javascript-2d2e4ad9df49

**Comment by nramirez** [comment]
Agree that we don't have to go with the specific implementation suggested, as long as the code can access the single instance of Discord concurrently, this could be implemented in many ways.

**Comment by TomasGonzalez** [comment]
> Agree that we don't have to go with the specific implementation suggested, as long as the code can access the single instance of Discord concurrently, this could be implemented in many ways.

My latest PR, actually contains an implementation of this as a side feature.
