### ISSUE TITLE
Weekly stats update should run after daily updates

### ISSUE THREAD

**Issue by nramirez** [kajahno/elprimobot#70]
Pick anytime after the daily update, could be anytime after the Daily update on Sunday Night, maybe Monday morning?

**Comment by kajahno** [comment]
Done, the crons:
```
DAILY_MESSAGE_CRON="30 0 0 * * *"
WEEKLY_MESSAGE_CRON="30 1 0 * * 1"
```

* Daily runs every day 30 seconds after midnight
* Weekly runs every Monday 30 seconds after 12:01 AM
