### ISSUE TITLE
Add problem body on weekly problem

### ISSUE THREAD

**Issue by Not4Now** [kajahno/elprimobot#9]
It would be nice for people that don't have premium to see the problem's description

**Comment by vetom** [comment]
I can see that Leetcode has a property `content` as part of their node `question` with the problem description. However, when I try the query below the answers come with the field empty. Looks like this feature will require some scraping from the page.

``` GraphQL
query dailyCodingQuestionRecords($year: Int!, $month: Int!) {
  dailyCodingChallengeV2(year: $year, month: $month) {
    weeklyChallenges {
      date
      userStatus
      link
      question {
        questionFrontendId
        difficulty
        content
        title
        titleSlug
      }
    }
  }
}
```

**Comment by kajahno** [comment]
@vetom  was this tested with a premium account? 

To be honest I'm not feeling very strong about this one, because it kind of gives a 'hint' to the problem. I feel that's kind of cheating somehow, what do you think?

**Comment by vetom** [comment]
For testing, I'm using Insomnia. I'm doing POSTs to `https://leetcode.com/graphql` using the queries with no auth like we are doing currently to get the daily and weekly challenge.

**Comment by kajahno** [comment]
I'll close this one for now.
